(add-hook 'html-mode-hook
          (lambda ()
            ;;(key-combo-mode 1)
            (setq imenu-create-index-function 'html-imenu-create-index)
            (setq tab-width 4)))

(add-hook 'web-mode-hook
          (lambda ()
            ;;(key-combo-mode 1)
            (setq web-mode-html-offset   2)
            (setq web-mode-css-offset    2)
            (setq web-mode-script-offset 2)
            (setq web-mode-php-offset    4)
            (setq web-mode-markup-indent-offset 2)
            (setq web-mode-css-indent-offset 2)
            (setq web-mode-code-indent-offset 4)
            (setq web-mode-disable-auto-pairing t)
            (setq web-mode-engines-alist
                  '(("php"    . "\\.tpl\\'"))
                  )
            (setq imenu-create-index-function 'html-imenu-create-index)
            ))

(setq auto-mode-alist
      (append (list
               ;; '("\\.c$" . c-mode)
               ;; '("\\.java$" . java-mode)
               '("\.js$" . web-mode)
               ;; '("\\.sgm$" . sgml-mode)
               ;; '("\\.sgml$" . sgml-mode)
              ;; '("\\.html$" . sgml-mode)
             ;;  '("\\.htm$" . sgml-mode)
               '("\.xml$" . web-mode)
               '("\.el$" . emacs-lisp-mode)
               '("\.php$" . php-mode)
               '("\.html$" . web-mode)
               '("\.stml$" . web-mode)
               '("\.ctp$" . web-mode)
               '("\.tpl$" . web-mode)
               ;; '("\.html$" . nxml-mode)
               ;; '("\.shtml$" . nxml-mode)
               ;; '("\.ctp$" . nxml-mode)
               '("\.css$" . css-mode)
               '("\.sql$" . sql-mode)
               '("\.csv$" . csv-mode)
               '("\.txt$" . text-mode)
               '("\.md$" . markdown-mode)
               '("\.eml$" . text-mode)
               '("\.htaccess"   . apache-mode)
               '("httpd\.conf"  . apache-mode)
               '("\.ini$" . ini-generic-mode)
               '("\.cnf$" . conf-mode)
               '("\.sh$"  . shell-script-mode)
               auto-mode-alist)))


